config:
  clientID: "oauth2-proxy"
  existingSecret: "oauth2-proxy-secrets"
  #cookieDomains: .test

extraArgs:
  provider: oidc
  oidc-issuer-url: https://keycloak.app.test/realms/zero-trust-local-platform
  redirect-url: https://auth.app.test/oauth2/callback

  #http-address: "0.0.0.0:4180"
  
  ssl-insecure-skip-verify: true
  insecure-oidc-skip-issuer-verification: true

  email-domain: "*"
  skip-provider-button: true


  #upstream: "static://200"
  #upstream: ""
  #upstream: "http://fastapi-service.default.svc.cluster.local:80"

  #cookie-domain: "auth.local"
  #cookie-domain: ".local"
  #cookie-domain: .test
  cookie-domain: ".app.test"
  #whitelist-domain: "fastapi.local"
  #whitelist-domain: ".test"
  whitelist-domain: ".app.test"

  cookie-secure: "true"
  cookie-samesite: "lax" # "lax" | "strict" breaks the callback; 'lax' is correct here
  #cookie-name: "_oauth2_proxy"
  
  #cookie-csrf-per-request: false
  #cookie-csrf-expire: 30m




  # oauth2-proxy must be aware it is behind ingress proxy
  reverse-proxy: "true"


  #trusted-ip: "0.0.0.0/0"


  #real-client-ip-header: "X-Forwarded-For"

  #pass-authorization-header: true
  set-authorization-header: "true"
  set-xauthrequest: "true"
  pass-access-token: "true"
  pass-user-headers: "true"

  #proxy-prefix: /oauth2
  #trusted-ip: 0.0.0.0/0




  #skip-jwt-bearer-tokens: "true"

  standard-logging: true
  auth-logging: true
  request-logging: true
  show-debug-on-error: true

hostAliases:
  - ip: "192.168.65.240"
    hostnames:
      - "keycloak.app.test"

service:
  type: ClusterIP

#ingress:
#  enabled: false   # IMPORTANT: we are managing ingress manually